version: "3"
services:
  ects-ros-dev:
    build: .
    container_name: "ects-ros-dev"
    user: 1000:1000
    volumes:
      - "./:/workspace"
    command: sleep infinity
      #    network_mode: "host"
    ports:
      - 9090:9090
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
